CREATE SCHEMA IF NOT EXISTS hr;

CREATE TABLE hr.department (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_code varchar(40) NOT NULL,
    department_name varchar(160) NOT NULL,
    parent_department_id bigint NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_department_code UNIQUE (department_code),
    CONSTRAINT fk_department_parent FOREIGN KEY (parent_department_id) REFERENCES hr.department (department_id),
    CONSTRAINT ck_department_name_nonempty CHECK (length(btrim(department_name)) > 0),
    CONSTRAINT ck_department_not_own_parent CHECK (parent_department_id IS NULL OR parent_department_id <> department_id),
    CONSTRAINT ck_department_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE hr.job_title (
    job_title_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title_code varchar(40) NOT NULL,
    job_title_name varchar(160) NOT NULL,
    description text NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_job_title_code UNIQUE (job_title_code),
    CONSTRAINT ck_job_title_name_nonempty CHECK (length(btrim(job_title_name)) > 0),
    CONSTRAINT ck_job_title_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE hr.work_shift (
    work_shift_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shift_code varchar(40) NOT NULL,
    shift_name varchar(120) NOT NULL,
    starts_at time NOT NULL,
    ends_at time NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_work_shift_code UNIQUE (shift_code),
    CONSTRAINT ck_work_shift_name_nonempty CHECK (length(btrim(shift_name)) > 0),
    CONSTRAINT ck_work_shift_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE hr.employee (
    employee_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code varchar(40) NOT NULL,
    full_name varchar(160) NOT NULL,
    phone_number varchar(30) NULL,
    email varchar(254) NULL,
    department_id bigint NULL,
    job_title_id bigint NULL,
    manager_employee_id bigint NULL,
    employment_status varchar(24) NOT NULL DEFAULT 'active',
    hired_on date NULL,
    terminated_on date NULL,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_employee_code UNIQUE (employee_code),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES hr.department (department_id),
    CONSTRAINT fk_employee_job_title FOREIGN KEY (job_title_id) REFERENCES hr.job_title (job_title_id),
    CONSTRAINT fk_employee_manager FOREIGN KEY (manager_employee_id) REFERENCES hr.employee (employee_id),
    CONSTRAINT ck_employee_full_name_nonempty CHECK (length(btrim(full_name)) > 0),
    CONSTRAINT ck_employee_not_own_manager CHECK (manager_employee_id IS NULL OR manager_employee_id <> employee_id),
    CONSTRAINT ck_employee_termination_date CHECK (terminated_on IS NULL OR hired_on IS NULL OR terminated_on >= hired_on),
    CONSTRAINT ck_employee_status CHECK (employment_status IN ('active', 'inactive', 'on_leave', 'terminated'))
);

CREATE TABLE hr.employment_contract (
    employment_contract_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_code varchar(60) NOT NULL,
    employee_id bigint NOT NULL,
    contract_type varchar(40) NOT NULL,
    effective_from date NOT NULL,
    effective_to date NULL,
    base_salary numeric(18, 2) NOT NULL,
    currency_code char(3) NOT NULL DEFAULT 'VND',
    status varchar(20) NOT NULL DEFAULT 'draft',
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_employment_contract_code UNIQUE (contract_code),
    CONSTRAINT uq_employment_contract_employee_pair UNIQUE (employment_contract_id, employee_id),
    CONSTRAINT fk_employment_contract_employee FOREIGN KEY (employee_id) REFERENCES hr.employee (employee_id),
    CONSTRAINT ck_employment_contract_dates CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_employment_contract_salary CHECK (base_salary >= 0),
    CONSTRAINT ck_employment_contract_status CHECK (status IN ('draft', 'active', 'expired', 'terminated', 'cancelled'))
);

CREATE TABLE hr.leave_request (
    leave_request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code varchar(60) NOT NULL,
    employee_id bigint NOT NULL,
    leave_type_code varchar(40) NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    is_paid boolean NOT NULL DEFAULT true,
    reason text NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    approver_user_id bigint NULL,
    decided_at timestamptz NULL,
    decision_note text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_leave_request_code UNIQUE (request_code),
    CONSTRAINT fk_leave_request_employee FOREIGN KEY (employee_id) REFERENCES hr.employee (employee_id),
    CONSTRAINT ck_leave_request_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_leave_request_status CHECK (status IN ('draft', 'pending', 'approved', 'rejected', 'cancelled'))
);

CREATE TABLE hr.employee_reward_discipline (
    employee_reward_discipline_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_code varchar(60) NOT NULL,
    employee_id bigint NOT NULL,
    event_type varchar(20) NOT NULL,
    effective_on date NOT NULL,
    reason text NOT NULL,
    amount numeric(18, 2) NULL,
    currency_code char(3) NOT NULL DEFAULT 'VND',
    status varchar(20) NOT NULL DEFAULT 'pending',
    approver_user_id bigint NULL,
    decided_at timestamptz NULL,
    decision_note text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_employee_reward_discipline_code UNIQUE (record_code),
    CONSTRAINT fk_employee_reward_discipline_employee FOREIGN KEY (employee_id) REFERENCES hr.employee (employee_id),
    CONSTRAINT ck_employee_reward_discipline_type CHECK (event_type IN ('reward', 'discipline')),
    CONSTRAINT ck_employee_reward_discipline_amount CHECK (amount IS NULL OR amount >= 0),
    CONSTRAINT ck_employee_reward_discipline_status CHECK (status IN ('draft', 'pending', 'approved', 'rejected', 'cancelled'))
);

CREATE TABLE hr.payroll_period (
    payroll_period_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_code varchar(40) NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    approved_by_user_id bigint NULL,
    approved_at timestamptz NULL,
    locked_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_payroll_period_code UNIQUE (period_code),
    CONSTRAINT uq_payroll_period_dates UNIQUE (starts_on, ends_on),
    CONSTRAINT ck_payroll_period_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_payroll_period_status CHECK (status IN ('draft', 'calculated', 'approved', 'locked'))
);

CREATE TABLE hr.payroll_record (
    payroll_record_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_period_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    employment_contract_id bigint NOT NULL,
    base_salary_snapshot numeric(18, 2) NOT NULL,
    unpaid_leave_days numeric(18, 6) NOT NULL DEFAULT 0,
    gross_amount numeric(18, 2) NOT NULL DEFAULT 0,
    deduction_amount numeric(18, 2) NOT NULL DEFAULT 0,
    net_amount numeric(18, 2) NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'draft',
    calculated_at timestamptz NULL,
    approved_by_user_id bigint NULL,
    approved_at timestamptz NULL,
    locked_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_payroll_record_period_employee UNIQUE (payroll_period_id, employee_id),
    CONSTRAINT fk_payroll_record_period FOREIGN KEY (payroll_period_id) REFERENCES hr.payroll_period (payroll_period_id),
    CONSTRAINT fk_payroll_record_employee FOREIGN KEY (employee_id) REFERENCES hr.employee (employee_id),
    CONSTRAINT fk_payroll_record_contract_employee FOREIGN KEY (employment_contract_id, employee_id) REFERENCES hr.employment_contract (employment_contract_id, employee_id),
    CONSTRAINT ck_payroll_record_amounts CHECK (base_salary_snapshot >= 0 AND unpaid_leave_days >= 0 AND gross_amount >= 0 AND deduction_amount >= 0 AND net_amount >= 0),
    CONSTRAINT ck_payroll_record_status CHECK (status IN ('draft', 'calculated', 'approved', 'locked'))
);

CREATE TABLE hr.payroll_line (
    payroll_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_record_id bigint NOT NULL,
    line_type varchar(40) NOT NULL,
    direction varchar(20) NOT NULL,
    line_label varchar(160) NOT NULL,
    quantity numeric(18, 6) NULL,
    unit_amount numeric(18, 2) NULL,
    amount numeric(18, 2) NOT NULL,
    source_type varchar(40) NULL,
    source_id bigint NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_payroll_line_record FOREIGN KEY (payroll_record_id) REFERENCES hr.payroll_record (payroll_record_id),
    CONSTRAINT ck_payroll_line_direction CHECK (direction IN ('earning', 'deduction')),
    CONSTRAINT ck_payroll_line_amount CHECK (amount >= 0 AND (quantity IS NULL OR quantity >= 0) AND (unit_amount IS NULL OR unit_amount >= 0)),
    CONSTRAINT ck_payroll_line_label_nonempty CHECK (length(btrim(line_label)) > 0)
);

CREATE INDEX ix_employee_department_status ON hr.employee (department_id, employment_status);
CREATE INDEX ix_employee_job_title ON hr.employee (job_title_id);
CREATE INDEX ix_employee_manager ON hr.employee (manager_employee_id);
CREATE INDEX ix_contract_employee_dates ON hr.employment_contract (employee_id, effective_from, effective_to);
CREATE INDEX ix_leave_request_employee_dates ON hr.leave_request (employee_id, starts_on, ends_on);
CREATE INDEX ix_leave_request_status_dates ON hr.leave_request (status, starts_on);
CREATE INDEX ix_reward_discipline_employee_date ON hr.employee_reward_discipline (employee_id, effective_on DESC);
CREATE INDEX ix_reward_discipline_status_date ON hr.employee_reward_discipline (status, effective_on);
CREATE INDEX ix_payroll_record_period_status ON hr.payroll_record (payroll_period_id, status);
CREATE INDEX ix_payroll_line_record ON hr.payroll_line (payroll_record_id);
