CREATE SCHEMA IF NOT EXISTS inventory;

CREATE TABLE inventory.unit_of_measure (
    unit_of_measure_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_code varchar(32) NOT NULL,
    unit_name varchar(100) NOT NULL,
    decimal_places smallint NOT NULL DEFAULT 3,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_unit_of_measure_code UNIQUE (unit_code),
    CONSTRAINT ck_unit_of_measure_decimal_places CHECK (decimal_places BETWEEN 0 AND 6),
    CONSTRAINT ck_unit_of_measure_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE inventory.item_category (
    item_category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code varchar(40) NOT NULL,
    category_name varchar(120) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_item_category_code UNIQUE (category_code),
    CONSTRAINT ck_item_category_name_nonempty CHECK (length(btrim(category_name)) > 0),
    CONSTRAINT ck_item_category_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE inventory.stock_item (
    stock_item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code varchar(60) NOT NULL,
    item_name varchar(180) NOT NULL,
    item_type varchar(24) NOT NULL,
    item_category_id bigint NULL,
    base_unit_of_measure_id bigint NOT NULL,
    lot_controlled boolean NOT NULL DEFAULT false,
    minimum_stock_quantity numeric(18, 6) NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    description text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_stock_item_code UNIQUE (item_code),
    CONSTRAINT fk_stock_item_category FOREIGN KEY (item_category_id) REFERENCES inventory.item_category (item_category_id),
    CONSTRAINT fk_stock_item_unit FOREIGN KEY (base_unit_of_measure_id) REFERENCES inventory.unit_of_measure (unit_of_measure_id),
    CONSTRAINT ck_stock_item_name_nonempty CHECK (length(btrim(item_name)) > 0),
    CONSTRAINT ck_stock_item_type CHECK (item_type IN ('raw_material', 'finished_product')),
    CONSTRAINT ck_stock_item_minimum_quantity CHECK (minimum_stock_quantity IS NULL OR minimum_stock_quantity >= 0),
    CONSTRAINT ck_stock_item_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE inventory.supplier (
    supplier_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code varchar(60) NOT NULL,
    supplier_name varchar(180) NOT NULL,
    phone_number varchar(30) NULL,
    email varchar(254) NULL,
    address text NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_supplier_code UNIQUE (supplier_code),
    CONSTRAINT ck_supplier_name_nonempty CHECK (length(btrim(supplier_name)) > 0),
    CONSTRAINT ck_supplier_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE inventory.warehouse (
    warehouse_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code varchar(40) NOT NULL,
    warehouse_name varchar(160) NOT NULL,
    address text NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_warehouse_code UNIQUE (warehouse_code),
    CONSTRAINT ck_warehouse_name_nonempty CHECK (length(btrim(warehouse_name)) > 0),
    CONSTRAINT ck_warehouse_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE inventory.warehouse_location (
    warehouse_location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_id bigint NOT NULL,
    location_code varchar(60) NOT NULL,
    location_name varchar(160) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_warehouse_location_code UNIQUE (warehouse_id, location_code),
    CONSTRAINT uq_warehouse_location_pair UNIQUE (warehouse_id, warehouse_location_id),
    CONSTRAINT fk_warehouse_location_warehouse FOREIGN KEY (warehouse_id) REFERENCES inventory.warehouse (warehouse_id),
    CONSTRAINT ck_warehouse_location_name_nonempty CHECK (length(btrim(location_name)) > 0),
    CONSTRAINT ck_warehouse_location_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE inventory.stock_lot (
    stock_lot_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_item_id bigint NOT NULL,
    lot_code varchar(80) NOT NULL,
    manufactured_on date NULL,
    expires_on date NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_stock_lot_item_code UNIQUE (stock_item_id, lot_code),
    CONSTRAINT uq_stock_lot_item_pair UNIQUE (stock_item_id, stock_lot_id),
    CONSTRAINT fk_stock_lot_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT ck_stock_lot_dates CHECK (expires_on IS NULL OR manufactured_on IS NULL OR expires_on >= manufactured_on),
    CONSTRAINT ck_stock_lot_status CHECK (status IN ('active', 'inactive', 'quarantined'))
);

CREATE TABLE inventory.receipt (
    receipt_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_code varchar(60) NOT NULL,
    warehouse_id bigint NOT NULL,
    supplier_id bigint NULL,
    source_module varchar(40) NULL,
    source_document_id bigint NULL,
    reference_number varchar(100) NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    idempotency_key varchar(120) NULL,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    posted_at timestamptz NULL,
    posted_by_user_id bigint NULL,
    CONSTRAINT uq_receipt_code UNIQUE (receipt_code),
    CONSTRAINT uq_receipt_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_receipt_warehouse FOREIGN KEY (warehouse_id) REFERENCES inventory.warehouse (warehouse_id),
    CONSTRAINT fk_receipt_supplier FOREIGN KEY (supplier_id) REFERENCES inventory.supplier (supplier_id),
    CONSTRAINT ck_receipt_source_pair CHECK ((source_module IS NULL) = (source_document_id IS NULL)),
    CONSTRAINT ck_receipt_status CHECK (status IN ('draft', 'pending', 'posted', 'cancelled'))
);

CREATE TABLE inventory.receipt_line (
    receipt_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id bigint NOT NULL,
    line_number integer NOT NULL,
    stock_item_id bigint NOT NULL,
    warehouse_location_id bigint NOT NULL,
    stock_lot_id bigint NULL,
    quantity numeric(18, 6) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_receipt_line_number UNIQUE (receipt_id, line_number),
    CONSTRAINT fk_receipt_line_receipt FOREIGN KEY (receipt_id) REFERENCES inventory.receipt (receipt_id),
    CONSTRAINT fk_receipt_line_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT fk_receipt_line_location FOREIGN KEY (warehouse_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_receipt_line_lot_item FOREIGN KEY (stock_item_id, stock_lot_id) REFERENCES inventory.stock_lot (stock_item_id, stock_lot_id),
    CONSTRAINT ck_receipt_line_number CHECK (line_number > 0),
    CONSTRAINT ck_receipt_line_quantity CHECK (quantity > 0)
);

CREATE TABLE inventory.issue (
    issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_code varchar(60) NOT NULL,
    warehouse_id bigint NOT NULL,
    source_module varchar(40) NULL,
    source_document_id bigint NULL,
    reason_code varchar(40) NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    idempotency_key varchar(120) NULL,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    posted_at timestamptz NULL,
    posted_by_user_id bigint NULL,
    CONSTRAINT uq_issue_code UNIQUE (issue_code),
    CONSTRAINT uq_issue_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_issue_warehouse FOREIGN KEY (warehouse_id) REFERENCES inventory.warehouse (warehouse_id),
    CONSTRAINT ck_issue_source_pair CHECK ((source_module IS NULL) = (source_document_id IS NULL)),
    CONSTRAINT ck_issue_status CHECK (status IN ('draft', 'pending', 'posted', 'cancelled'))
);

CREATE TABLE inventory.issue_line (
    issue_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id bigint NOT NULL,
    line_number integer NOT NULL,
    stock_item_id bigint NOT NULL,
    warehouse_location_id bigint NOT NULL,
    stock_lot_id bigint NULL,
    quantity numeric(18, 6) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_issue_line_number UNIQUE (issue_id, line_number),
    CONSTRAINT fk_issue_line_issue FOREIGN KEY (issue_id) REFERENCES inventory.issue (issue_id),
    CONSTRAINT fk_issue_line_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT fk_issue_line_location FOREIGN KEY (warehouse_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_issue_line_lot_item FOREIGN KEY (stock_item_id, stock_lot_id) REFERENCES inventory.stock_lot (stock_item_id, stock_lot_id),
    CONSTRAINT ck_issue_line_number CHECK (line_number > 0),
    CONSTRAINT ck_issue_line_quantity CHECK (quantity > 0)
);

CREATE TABLE inventory.transfer (
    transfer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_code varchar(60) NOT NULL,
    source_warehouse_id bigint NOT NULL,
    destination_warehouse_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    idempotency_key varchar(120) NULL,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    posted_at timestamptz NULL,
    posted_by_user_id bigint NULL,
    CONSTRAINT uq_transfer_code UNIQUE (transfer_code),
    CONSTRAINT uq_transfer_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_transfer_source_warehouse FOREIGN KEY (source_warehouse_id) REFERENCES inventory.warehouse (warehouse_id),
    CONSTRAINT fk_transfer_destination_warehouse FOREIGN KEY (destination_warehouse_id) REFERENCES inventory.warehouse (warehouse_id),
    CONSTRAINT ck_transfer_status CHECK (status IN ('draft', 'pending', 'posted', 'cancelled'))
);

CREATE TABLE inventory.transfer_line (
    transfer_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_id bigint NOT NULL,
    line_number integer NOT NULL,
    stock_item_id bigint NOT NULL,
    stock_lot_id bigint NULL,
    source_location_id bigint NOT NULL,
    destination_location_id bigint NOT NULL,
    quantity numeric(18, 6) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_transfer_line_number UNIQUE (transfer_id, line_number),
    CONSTRAINT fk_transfer_line_transfer FOREIGN KEY (transfer_id) REFERENCES inventory.transfer (transfer_id),
    CONSTRAINT fk_transfer_line_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT fk_transfer_line_source_location FOREIGN KEY (source_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_transfer_line_destination_location FOREIGN KEY (destination_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_transfer_line_lot_item FOREIGN KEY (stock_item_id, stock_lot_id) REFERENCES inventory.stock_lot (stock_item_id, stock_lot_id),
    CONSTRAINT ck_transfer_line_number CHECK (line_number > 0),
    CONSTRAINT ck_transfer_line_locations_differ CHECK (source_location_id <> destination_location_id),
    CONSTRAINT ck_transfer_line_quantity CHECK (quantity > 0)
);

CREATE TABLE inventory.stocktake (
    stocktake_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_code varchar(60) NOT NULL,
    warehouse_id bigint NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    started_at timestamptz NULL,
    submitted_at timestamptz NULL,
    posted_at timestamptz NULL,
    posted_by_user_id bigint NULL,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_stocktake_code UNIQUE (stocktake_code),
    CONSTRAINT fk_stocktake_warehouse FOREIGN KEY (warehouse_id) REFERENCES inventory.warehouse (warehouse_id),
    CONSTRAINT ck_stocktake_status CHECK (status IN ('draft', 'counting', 'submitted', 'approved', 'posted', 'cancelled'))
);

CREATE TABLE inventory.stocktake_line (
    stocktake_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stocktake_id bigint NOT NULL,
    line_number integer NOT NULL,
    stock_item_id bigint NOT NULL,
    warehouse_location_id bigint NOT NULL,
    stock_lot_id bigint NULL,
    system_quantity numeric(18, 6) NOT NULL,
    counted_quantity numeric(18, 6) NULL,
    counted_at timestamptz NULL,
    counted_by_user_id bigint NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_stocktake_line_number UNIQUE (stocktake_id, line_number),
    CONSTRAINT fk_stocktake_line_session FOREIGN KEY (stocktake_id) REFERENCES inventory.stocktake (stocktake_id),
    CONSTRAINT fk_stocktake_line_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT fk_stocktake_line_location FOREIGN KEY (warehouse_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_stocktake_line_lot_item FOREIGN KEY (stock_item_id, stock_lot_id) REFERENCES inventory.stock_lot (stock_item_id, stock_lot_id),
    CONSTRAINT ck_stocktake_line_number CHECK (line_number > 0),
    CONSTRAINT ck_stocktake_line_quantities CHECK (system_quantity >= 0 AND (counted_quantity IS NULL OR counted_quantity >= 0))
);

CREATE UNIQUE INDEX uq_stocktake_line_without_lot
    ON inventory.stocktake_line (stocktake_id, stock_item_id, warehouse_location_id)
    WHERE stock_lot_id IS NULL;

CREATE UNIQUE INDEX uq_stocktake_line_with_lot
    ON inventory.stocktake_line (stocktake_id, stock_item_id, warehouse_location_id, stock_lot_id)
    WHERE stock_lot_id IS NOT NULL;

CREATE TABLE inventory.stock_movement (
    stock_movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_document_type varchar(40) NOT NULL,
    source_document_id bigint NOT NULL,
    source_document_line_id bigint NOT NULL,
    movement_leg varchar(20) NOT NULL DEFAULT 'single',
    movement_type varchar(32) NOT NULL,
    stock_item_id bigint NOT NULL,
    warehouse_location_id bigint NOT NULL,
    stock_lot_id bigint NULL,
    quantity_delta numeric(18, 6) NOT NULL,
    posted_at timestamptz NOT NULL DEFAULT now(),
    posted_by_user_id bigint NULL,
    reversal_of_movement_id bigint NULL,
    idempotency_key varchar(120) NOT NULL,
    CONSTRAINT uq_stock_movement_source_leg UNIQUE (source_document_type, source_document_id, source_document_line_id, movement_leg),
    CONSTRAINT uq_stock_movement_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_stock_movement_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT fk_stock_movement_location FOREIGN KEY (warehouse_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_stock_movement_lot_item FOREIGN KEY (stock_item_id, stock_lot_id) REFERENCES inventory.stock_lot (stock_item_id, stock_lot_id),
    CONSTRAINT fk_stock_movement_reversal FOREIGN KEY (reversal_of_movement_id) REFERENCES inventory.stock_movement (stock_movement_id),
    CONSTRAINT ck_stock_movement_quantity_nonzero CHECK (quantity_delta <> 0),
    CONSTRAINT ck_stock_movement_receipt_positive CHECK (movement_type <> 'receipt' OR quantity_delta > 0),
    CONSTRAINT ck_stock_movement_issue_negative CHECK (movement_type <> 'issue' OR quantity_delta < 0),
    CONSTRAINT ck_stock_movement_transfer_direction CHECK (movement_type <> 'transfer' OR ((movement_leg = 'source' AND quantity_delta < 0) OR (movement_leg = 'destination' AND quantity_delta > 0))),
    CONSTRAINT ck_stock_movement_leg CHECK (movement_leg IN ('single', 'source', 'destination', 'adjustment', 'reversal')),
    CONSTRAINT ck_stock_movement_type CHECK (movement_type IN ('receipt', 'issue', 'transfer', 'stocktake_adjustment', 'return', 'reversal'))
);

CREATE TABLE inventory.stock_balance (
    stock_balance_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_item_id bigint NOT NULL,
    warehouse_location_id bigint NOT NULL,
    stock_lot_id bigint NULL,
    on_hand_quantity numeric(18, 6) NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fk_stock_balance_item FOREIGN KEY (stock_item_id) REFERENCES inventory.stock_item (stock_item_id),
    CONSTRAINT fk_stock_balance_location FOREIGN KEY (warehouse_location_id) REFERENCES inventory.warehouse_location (warehouse_location_id),
    CONSTRAINT fk_stock_balance_lot_item FOREIGN KEY (stock_item_id, stock_lot_id) REFERENCES inventory.stock_lot (stock_item_id, stock_lot_id),
    CONSTRAINT ck_stock_balance_nonnegative CHECK (on_hand_quantity >= 0)
);

CREATE UNIQUE INDEX uq_stock_balance_without_lot
    ON inventory.stock_balance (stock_item_id, warehouse_location_id)
    WHERE stock_lot_id IS NULL;

CREATE UNIQUE INDEX uq_stock_balance_with_lot
    ON inventory.stock_balance (stock_item_id, warehouse_location_id, stock_lot_id)
    WHERE stock_lot_id IS NOT NULL;

CREATE INDEX ix_stock_item_type_status ON inventory.stock_item (item_type, status);
CREATE INDEX ix_stock_lot_expiry ON inventory.stock_lot (expires_on) WHERE expires_on IS NOT NULL;
CREATE INDEX ix_receipt_warehouse_status_date ON inventory.receipt (warehouse_id, status, created_at DESC);
CREATE INDEX ix_receipt_line_item ON inventory.receipt_line (stock_item_id, receipt_id);
CREATE INDEX ix_issue_warehouse_status_date ON inventory.issue (warehouse_id, status, created_at DESC);
CREATE INDEX ix_issue_source_reference ON inventory.issue (source_module, source_document_id);
CREATE INDEX ix_issue_line_item ON inventory.issue_line (stock_item_id, issue_id);
CREATE INDEX ix_transfer_status_date ON inventory.transfer (status, created_at DESC);
CREATE INDEX ix_stocktake_warehouse_status ON inventory.stocktake (warehouse_id, status);
CREATE INDEX ix_stocktake_line_item_location ON inventory.stocktake_line (stock_item_id, warehouse_location_id);
CREATE INDEX ix_stock_movement_item_location_time ON inventory.stock_movement (stock_item_id, warehouse_location_id, posted_at DESC);
CREATE INDEX ix_stock_movement_lot_time ON inventory.stock_movement (stock_lot_id, posted_at DESC) WHERE stock_lot_id IS NOT NULL;
CREATE INDEX ix_stock_movement_source ON inventory.stock_movement (source_document_type, source_document_id);
CREATE INDEX ix_stock_balance_item_location ON inventory.stock_balance (stock_item_id, warehouse_location_id);
