CREATE SCHEMA IF NOT EXISTS quality_cost;

CREATE TABLE quality_cost.cost_rule_version (
    rule_version_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code varchar(60) NOT NULL UNIQUE,
    material_valuation_method varchar(40) NOT NULL,
    labor_basis varchar(40) NOT NULL,
    overhead_basis varchar(40) NOT NULL,
    defective_policy varchar(40) NOT NULL,
    currency_code varchar(3) NOT NULL DEFAULT 'VND',
    rounding_scale smallint NOT NULL DEFAULT 2,
    effective_from date NOT NULL,
    effective_to date,
    status varchar(20) NOT NULL DEFAULT 'draft',
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_cost_rule_rounding CHECK (rounding_scale BETWEEN 0 AND 6),
    CONSTRAINT ck_cost_rule_dates CHECK (effective_to IS NULL OR effective_to >= effective_from),
    CONSTRAINT ck_cost_rule_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE quality_cost.cost_period (
    cost_period_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_code varchar(60) NOT NULL UNIQUE,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    rule_version_id bigint NOT NULL REFERENCES quality_cost.cost_rule_version(rule_version_id),
    status varchar(20) NOT NULL DEFAULT 'draft',
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_cost_period_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_cost_period_status CHECK (status IN ('draft', 'open', 'calculating', 'calculated', 'approved', 'locked', 'cancelled'))
);

CREATE TABLE quality_cost.quality_inspection (
    inspection_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inspection_code varchar(60) NOT NULL UNIQUE,
    production_order_id bigint,
    production_output_id bigint,
    stock_item_id bigint NOT NULL,
    lot_code varchar(120),
    inspected_quantity numeric(20,6) NOT NULL,
    good_quantity numeric(20,6) NOT NULL DEFAULT 0,
    defective_quantity numeric(20,6) NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'draft',
    inspected_on date NOT NULL,
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_quality_inspection_quantities CHECK (inspected_quantity > 0 AND good_quantity >= 0 AND defective_quantity >= 0 AND good_quantity + defective_quantity <= inspected_quantity),
    CONSTRAINT ck_quality_inspection_status CHECK (status IN ('draft', 'submitted', 'passed', 'failed', 'held', 'released', 'cancelled'))
);

CREATE TABLE quality_cost.nonconformance (
    nonconformance_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nonconformance_code varchar(60) NOT NULL UNIQUE,
    inspection_id bigint NOT NULL REFERENCES quality_cost.quality_inspection(inspection_id),
    defect_code varchar(60) NOT NULL,
    quantity numeric(20,6) NOT NULL,
    disposition varchar(30) NOT NULL DEFAULT 'hold',
    status varchar(20) NOT NULL DEFAULT 'open',
    resolved_on date,
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_nonconformance_quantity CHECK (quantity > 0),
    CONSTRAINT ck_nonconformance_disposition CHECK (disposition IN ('hold', 'rework', 'scrap', 'return', 'release')),
    CONSTRAINT ck_nonconformance_status CHECK (status IN ('open', 'in_progress', 'resolved', 'cancelled'))
);

CREATE TABLE quality_cost.overhead_pool (
    overhead_pool_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_period_id bigint NOT NULL REFERENCES quality_cost.cost_period(cost_period_id),
    pool_code varchar(60) NOT NULL,
    pool_name varchar(180) NOT NULL,
    amount numeric(20,2) NOT NULL,
    allocation_basis varchar(40) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_overhead_pool_code UNIQUE (cost_period_id, pool_code),
    CONSTRAINT ck_overhead_pool_amount CHECK (amount >= 0),
    CONSTRAINT ck_overhead_pool_status CHECK (status IN ('draft', 'approved', 'locked'))
);

CREATE TABLE quality_cost.cost_calculation (
    cost_calculation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_period_id bigint NOT NULL REFERENCES quality_cost.cost_period(cost_period_id),
    production_order_id bigint,
    stock_item_id bigint NOT NULL,
    stock_item_code varchar(80),
    stock_item_name varchar(240),
    good_quantity numeric(20,6) NOT NULL,
    material_cost numeric(20,2) NOT NULL DEFAULT 0,
    direct_labor_cost numeric(20,2) NOT NULL DEFAULT 0,
    overhead_cost numeric(20,2) NOT NULL DEFAULT 0,
    adjustment_amount numeric(20,2) NOT NULL DEFAULT 0,
    total_cost numeric(20,2) NOT NULL DEFAULT 0,
    unit_cost numeric(20,6) NOT NULL DEFAULT 0,
    status varchar(20) NOT NULL DEFAULT 'calculated',
    calculated_at timestamptz NOT NULL DEFAULT now(),
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_cost_calculation_quantity CHECK (good_quantity > 0),
    CONSTRAINT ck_cost_calculation_status CHECK (status IN ('calculated', 'approved', 'locked', 'cancelled'))
);

CREATE TABLE quality_cost.cost_calculation_line (
    cost_calculation_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_calculation_id bigint NOT NULL REFERENCES quality_cost.cost_calculation(cost_calculation_id) ON DELETE CASCADE,
    line_type varchar(30) NOT NULL,
    source_module varchar(30) NOT NULL,
    source_id bigint,
    description varchar(240) NOT NULL,
    quantity numeric(20,6),
    unit_cost numeric(20,6),
    amount numeric(20,2) NOT NULL,
    CONSTRAINT ck_cost_line_type CHECK (line_type IN ('material', 'labor', 'overhead', 'adjustment'))
);

CREATE TABLE quality_cost.cost_adjustment (
    cost_adjustment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cost_calculation_id bigint NOT NULL REFERENCES quality_cost.cost_calculation(cost_calculation_id),
    adjustment_code varchar(60) NOT NULL UNIQUE,
    amount numeric(20,2) NOT NULL,
    reason varchar(1000) NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    created_by_user_id bigint NOT NULL,
    approved_by_user_id bigint,
    created_at timestamptz NOT NULL DEFAULT now(),
    approved_at timestamptz,
    CONSTRAINT ck_cost_adjustment_status CHECK (status IN ('draft', 'pending', 'approved', 'rejected'))
);

CREATE TABLE quality_cost.price_proposal (
    price_proposal_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_code varchar(60) NOT NULL UNIQUE,
    cost_period_id bigint NOT NULL REFERENCES quality_cost.cost_period(cost_period_id),
    stock_item_id bigint NOT NULL,
    stock_item_code varchar(80),
    stock_item_name varchar(240),
    unit_cost numeric(20,6) NOT NULL,
    margin_percent numeric(9,4) NOT NULL DEFAULT 0,
    proposed_price numeric(20,2) NOT NULL,
    currency_code varchar(3) NOT NULL DEFAULT 'VND',
    status varchar(20) NOT NULL DEFAULT 'draft',
    effective_on date NOT NULL,
    notes varchar(2000),
    created_by_user_id bigint NOT NULL,
    updated_by_user_id bigint NOT NULL,
    approved_by_user_id bigint,
    approved_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_price_proposal_values CHECK (unit_cost >= 0 AND proposed_price >= 0 AND margin_percent >= 0),
    CONSTRAINT ck_price_proposal_status CHECK (status IN ('draft', 'pending', 'approved', 'rejected', 'published', 'cancelled'))
);

CREATE INDEX ix_quality_inspection_status_date ON quality_cost.quality_inspection(status, inspected_on DESC);
CREATE INDEX ix_nonconformance_inspection_status ON quality_cost.nonconformance(inspection_id, status);
CREATE INDEX ix_cost_period_status_dates ON quality_cost.cost_period(status, starts_on DESC);
CREATE INDEX ix_cost_calculation_period_item ON quality_cost.cost_calculation(cost_period_id, stock_item_id);
CREATE INDEX ix_price_proposal_period_status ON quality_cost.price_proposal(cost_period_id, status);
