CREATE SCHEMA IF NOT EXISTS production;

CREATE TABLE production.production_plan (
    production_plan_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code varchar(60) NOT NULL,
    plan_name varchar(180) NOT NULL,
    planned_on date NOT NULL,
    starts_on date NOT NULL,
    ends_on date NOT NULL,
    status varchar(24) NOT NULL DEFAULT 'draft',
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_production_plan_code UNIQUE (plan_code),
    CONSTRAINT ck_production_plan_name_nonempty CHECK (length(btrim(plan_name)) > 0),
    CONSTRAINT ck_production_plan_dates CHECK (ends_on >= starts_on),
    CONSTRAINT ck_production_plan_status CHECK (status IN ('draft', 'approved', 'released', 'completed', 'cancelled'))
);

CREATE TABLE production.production_plan_line (
    production_plan_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_plan_id bigint NOT NULL,
    line_number integer NOT NULL,
    stock_item_id bigint NOT NULL,
    stock_item_code_snapshot varchar(60) NULL,
    stock_item_name_snapshot varchar(180) NULL,
    unit_code_snapshot varchar(32) NOT NULL,
    target_quantity numeric(18, 6) NOT NULL,
    required_on date NULL,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_production_plan_line_number UNIQUE (production_plan_id, line_number),
    CONSTRAINT uq_production_plan_line_item_pair UNIQUE (production_plan_line_id, stock_item_id),
    CONSTRAINT fk_production_plan_line_plan FOREIGN KEY (production_plan_id) REFERENCES production.production_plan (production_plan_id),
    CONSTRAINT ck_production_plan_line_number CHECK (line_number > 0),
    CONSTRAINT ck_production_plan_line_quantity CHECK (target_quantity > 0)
);

CREATE TABLE production.bom (
    bom_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_code varchar(60) NOT NULL,
    stock_item_id bigint NOT NULL,
    version_number integer NOT NULL,
    base_quantity numeric(18, 6) NOT NULL DEFAULT 1,
    unit_code_snapshot varchar(32) NOT NULL,
    valid_from date NOT NULL,
    valid_to date NULL,
    status varchar(20) NOT NULL DEFAULT 'draft',
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_bom_code_version UNIQUE (bom_code, version_number),
    CONSTRAINT uq_bom_item_version UNIQUE (stock_item_id, version_number),
    CONSTRAINT uq_bom_id_item_pair UNIQUE (bom_id, stock_item_id),
    CONSTRAINT ck_bom_version_number CHECK (version_number > 0),
    CONSTRAINT ck_bom_base_quantity CHECK (base_quantity > 0),
    CONSTRAINT ck_bom_dates CHECK (valid_to IS NULL OR valid_to >= valid_from),
    CONSTRAINT ck_bom_status CHECK (status IN ('draft', 'active', 'inactive'))
);

CREATE TABLE production.bom_line (
    bom_line_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bom_id bigint NOT NULL,
    line_number integer NOT NULL,
    material_stock_item_id bigint NOT NULL,
    unit_code_snapshot varchar(32) NOT NULL,
    quantity_per_base numeric(18, 6) NOT NULL,
    scrap_percent numeric(5, 2) NOT NULL DEFAULT 0,
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_bom_line_number UNIQUE (bom_id, line_number),
    CONSTRAINT uq_bom_line_bom_item_pair UNIQUE (bom_line_id, bom_id, material_stock_item_id),
    CONSTRAINT fk_bom_line_bom FOREIGN KEY (bom_id) REFERENCES production.bom (bom_id),
    CONSTRAINT ck_bom_line_number CHECK (line_number > 0),
    CONSTRAINT ck_bom_line_quantity CHECK (quantity_per_base > 0),
    CONSTRAINT ck_bom_line_scrap_percent CHECK (scrap_percent >= 0 AND scrap_percent <= 100)
);

CREATE TABLE production.production_order (
    production_order_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code varchar(60) NOT NULL,
    production_plan_line_id bigint NOT NULL,
    stock_item_id bigint NOT NULL,
    bom_id bigint NOT NULL,
    target_quantity numeric(18, 6) NOT NULL,
    unit_code_snapshot varchar(32) NOT NULL,
    planned_starts_on date NOT NULL,
    planned_ends_on date NOT NULL,
    production_line_name varchar(120) NULL,
    status varchar(24) NOT NULL DEFAULT 'draft',
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    released_at timestamptz NULL,
    CONSTRAINT uq_production_order_code UNIQUE (order_code),
    CONSTRAINT uq_production_order_id_bom UNIQUE (production_order_id, bom_id),
    CONSTRAINT uq_production_order_id_item UNIQUE (production_order_id, stock_item_id),
    CONSTRAINT fk_production_order_plan_line_item FOREIGN KEY (production_plan_line_id, stock_item_id) REFERENCES production.production_plan_line (production_plan_line_id, stock_item_id),
    CONSTRAINT fk_production_order_bom_item FOREIGN KEY (bom_id, stock_item_id) REFERENCES production.bom (bom_id, stock_item_id),
    CONSTRAINT ck_production_order_quantity CHECK (target_quantity > 0),
    CONSTRAINT ck_production_order_dates CHECK (planned_ends_on >= planned_starts_on),
    CONSTRAINT ck_production_order_status CHECK (status IN ('draft', 'planned', 'released', 'in_progress', 'paused', 'completed', 'cancelled'))
);

CREATE TABLE production.production_order_material_requirement (
    production_order_material_requirement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id bigint NOT NULL,
    bom_id bigint NOT NULL,
    bom_line_id bigint NOT NULL,
    material_stock_item_id bigint NOT NULL,
    unit_code_snapshot varchar(32) NOT NULL,
    base_quantity_snapshot numeric(18, 6) NOT NULL,
    scrap_percent_snapshot numeric(5, 2) NOT NULL DEFAULT 0,
    required_quantity numeric(18, 6) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_order_material_requirement_bom_line UNIQUE (production_order_id, bom_line_id),
    CONSTRAINT fk_order_material_requirement_order_bom FOREIGN KEY (production_order_id, bom_id) REFERENCES production.production_order (production_order_id, bom_id),
    CONSTRAINT fk_order_material_requirement_bom_line_item FOREIGN KEY (bom_line_id, bom_id, material_stock_item_id) REFERENCES production.bom_line (bom_line_id, bom_id, material_stock_item_id),
    CONSTRAINT ck_order_material_requirement_quantities CHECK (base_quantity_snapshot > 0 AND scrap_percent_snapshot >= 0 AND scrap_percent_snapshot <= 100 AND required_quantity > 0)
);

CREATE TABLE production.production_order_event (
    production_order_event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id bigint NOT NULL,
    event_type varchar(40) NOT NULL,
    previous_status varchar(24) NULL,
    new_status varchar(24) NULL,
    note text NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    actor_user_id bigint NULL,
    idempotency_key varchar(120) NULL,
    CONSTRAINT uq_production_order_event_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_production_order_event_order FOREIGN KEY (production_order_id) REFERENCES production.production_order (production_order_id),
    CONSTRAINT ck_production_order_event_type CHECK (event_type IN ('status_changed', 'progress_note', 'started', 'paused', 'resumed', 'completed', 'cancelled'))
);

CREATE TABLE production.production_assignment (
    production_assignment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    work_shift_id bigint NULL,
    assignment_name varchar(120) NULL,
    starts_at timestamptz NOT NULL,
    ends_at timestamptz NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'planned',
    notes text NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT fk_production_assignment_order FOREIGN KEY (production_order_id) REFERENCES production.production_order (production_order_id),
    CONSTRAINT ck_production_assignment_dates CHECK (ends_at > starts_at),
    CONSTRAINT ck_production_assignment_status CHECK (status IN ('planned', 'active', 'completed', 'cancelled'))
);

CREATE TABLE production.material_consumption (
    material_consumption_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id bigint NOT NULL,
    material_stock_item_id bigint NOT NULL,
    inventory_issue_line_id bigint NOT NULL,
    unit_code_snapshot varchar(32) NOT NULL,
    consumed_quantity numeric(18, 6) NOT NULL,
    consumed_at timestamptz NOT NULL DEFAULT now(),
    recorded_by_user_id bigint NULL,
    idempotency_key varchar(120) NOT NULL,
    notes text NULL,
    CONSTRAINT uq_material_consumption_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_material_consumption_order FOREIGN KEY (production_order_id) REFERENCES production.production_order (production_order_id),
    CONSTRAINT ck_material_consumption_quantity CHECK (consumed_quantity > 0)
);

CREATE TABLE production.production_output (
    production_output_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id bigint NOT NULL,
    stock_item_id bigint NOT NULL,
    lot_code_snapshot varchar(80) NOT NULL,
    manufactured_on date NOT NULL,
    expires_on date NULL,
    good_quantity numeric(18, 6) NOT NULL DEFAULT 0,
    defective_quantity numeric(18, 6) NOT NULL DEFAULT 0,
    inventory_stock_lot_id bigint NULL,
    inventory_receipt_id bigint NULL,
    status varchar(24) NOT NULL DEFAULT 'draft',
    idempotency_key varchar(120) NOT NULL,
    recorded_at timestamptz NOT NULL DEFAULT now(),
    recorded_by_user_id bigint NULL,
    received_at timestamptz NULL,
    notes text NULL,
    CONSTRAINT uq_production_output_order_lot UNIQUE (production_order_id, lot_code_snapshot),
    CONSTRAINT uq_production_output_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT fk_production_output_order_item FOREIGN KEY (production_order_id, stock_item_id) REFERENCES production.production_order (production_order_id, stock_item_id),
    CONSTRAINT ck_production_output_quantities CHECK (good_quantity >= 0 AND defective_quantity >= 0 AND (good_quantity + defective_quantity) > 0),
    CONSTRAINT ck_production_output_dates CHECK (expires_on IS NULL OR expires_on >= manufactured_on),
    CONSTRAINT ck_production_output_status CHECK (status IN ('draft', 'pending_receipt', 'received', 'failed', 'cancelled'))
);

CREATE UNIQUE INDEX uq_production_output_inventory_lot
    ON production.production_output (inventory_stock_lot_id)
    WHERE inventory_stock_lot_id IS NOT NULL;

CREATE INDEX ix_production_plan_status_dates ON production.production_plan (status, starts_on, ends_on);
CREATE INDEX ix_production_plan_line_item ON production.production_plan_line (stock_item_id);
CREATE INDEX ix_bom_active_item_date ON production.bom (stock_item_id, status, valid_from, valid_to);
CREATE INDEX ix_bom_line_material ON production.bom_line (material_stock_item_id);
CREATE INDEX ix_production_order_status_dates ON production.production_order (status, planned_starts_on, planned_ends_on);
CREATE INDEX ix_production_order_plan_line ON production.production_order (production_plan_line_id);
CREATE INDEX ix_order_material_requirement_order ON production.production_order_material_requirement (production_order_id);
CREATE INDEX ix_order_material_requirement_material ON production.production_order_material_requirement (material_stock_item_id);
CREATE INDEX ix_production_order_event_timeline ON production.production_order_event (production_order_id, occurred_at);
CREATE INDEX ix_production_assignment_employee_time ON production.production_assignment (employee_id, starts_at, ends_at);
CREATE INDEX ix_production_assignment_order_status ON production.production_assignment (production_order_id, status);
CREATE INDEX ix_material_consumption_order_time ON production.material_consumption (production_order_id, consumed_at);
CREATE INDEX ix_material_consumption_item_time ON production.material_consumption (material_stock_item_id, consumed_at);
CREATE INDEX ix_production_output_order_time ON production.production_output (production_order_id, recorded_at);
CREATE INDEX ix_production_output_item_lot ON production.production_output (stock_item_id, lot_code_snapshot);
