CREATE SCHEMA IF NOT EXISTS identity;

CREATE TABLE identity.user_account (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL,
    password_hash varchar(255) NOT NULL,
    employee_id bigint NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    failed_login_count integer NOT NULL DEFAULT 0,
    locked_until timestamptz NULL,
    last_login_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_user_account_username UNIQUE (username),
    CONSTRAINT uq_user_account_employee_id UNIQUE (employee_id),
    CONSTRAINT ck_user_account_username_normalized CHECK (username = lower(btrim(username))),
    CONSTRAINT ck_user_account_status CHECK (status IN ('active', 'locked', 'disabled')),
    CONSTRAINT ck_user_account_failed_login_count CHECK (failed_login_count >= 0)
);

CREATE TABLE identity.role (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code varchar(80) NOT NULL,
    display_name varchar(120) NOT NULL,
    description text NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by_user_id bigint NULL,
    CONSTRAINT uq_role_role_code UNIQUE (role_code),
    CONSTRAINT ck_role_role_code_normalized CHECK (role_code = lower(btrim(role_code)) AND role_code ~ '^[a-z][a-z0-9_]*$'),
    CONSTRAINT ck_role_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE identity.permission (
    permission_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code varchar(100) NOT NULL,
    module_code varchar(40) NOT NULL,
    action_code varchar(40) NOT NULL,
    description text NULL,
    status varchar(20) NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by_user_id bigint NULL,
    CONSTRAINT uq_permission_permission_code UNIQUE (permission_code),
    CONSTRAINT ck_permission_code_normalized CHECK (permission_code = lower(btrim(permission_code)) AND permission_code ~ '^[a-z][a-z0-9_]*$'),
    CONSTRAINT ck_permission_module_code_normalized CHECK (module_code = lower(btrim(module_code)) AND module_code ~ '^[a-z][a-z0-9_]*$'),
    CONSTRAINT ck_permission_action_code_normalized CHECK (action_code = lower(btrim(action_code)) AND action_code ~ '^[a-z][a-z0-9_]*$'),
    CONSTRAINT ck_permission_status CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE identity.user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_at timestamptz NOT NULL DEFAULT now(),
    assigned_by_user_id bigint NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES identity.user_account (user_id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES identity.role (role_id),
    CONSTRAINT fk_user_role_assigned_by FOREIGN KEY (assigned_by_user_id) REFERENCES identity.user_account (user_id)
);

CREATE TABLE identity.role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    granted_at timestamptz NOT NULL DEFAULT now(),
    granted_by_user_id bigint NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES identity.role (role_id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES identity.permission (permission_id),
    CONSTRAINT fk_role_permission_granted_by FOREIGN KEY (granted_by_user_id) REFERENCES identity.user_account (user_id)
);

CREATE TABLE identity.user_session (
    session_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    session_secret_hash varchar(255) NOT NULL,
    issued_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz NULL,
    last_used_at timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_user_session_secret_hash UNIQUE (session_secret_hash),
    CONSTRAINT fk_user_session_user FOREIGN KEY (user_id) REFERENCES identity.user_account (user_id),
    CONSTRAINT ck_user_session_expiry CHECK (expires_at > issued_at)
);

CREATE TABLE identity.audit_log (
    audit_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint NULL,
    module_code varchar(40) NOT NULL,
    action_code varchar(80) NOT NULL,
    entity_type varchar(80) NOT NULL,
    entity_id varchar(120) NULL,
    correlation_id varchar(120) NULL,
    occurred_at timestamptz NOT NULL DEFAULT now(),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT fk_audit_log_actor FOREIGN KEY (actor_user_id) REFERENCES identity.user_account (user_id) ON DELETE SET NULL,
    CONSTRAINT ck_audit_log_metadata_object CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX ix_user_account_status ON identity.user_account (status);
CREATE INDEX ix_user_session_user_expiry ON identity.user_session (user_id, expires_at);
CREATE INDEX ix_user_session_active_expiry ON identity.user_session (expires_at) WHERE revoked_at IS NULL;
CREATE INDEX ix_audit_log_actor_time ON identity.audit_log (actor_user_id, occurred_at DESC);
CREATE INDEX ix_audit_log_entity ON identity.audit_log (entity_type, entity_id, occurred_at DESC);
CREATE INDEX ix_audit_log_module_action_time ON identity.audit_log (module_code, action_code, occurred_at DESC);
