CREATE TABLE identity.registration_request (
    registration_request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(160) NOT NULL,
    work_email varchar(254) NOT NULL,
    username varchar(80) NOT NULL,
    employee_code varchar(40) NULL,
    password_hash varchar(255) NULL,
    status varchar(20) NOT NULL DEFAULT 'pending',
    requested_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    reviewed_at timestamptz NULL,
    reviewed_by_user_id bigint NULL,
    review_note varchar(500) NULL,
    CONSTRAINT fk_registration_reviewed_by FOREIGN KEY (reviewed_by_user_id) REFERENCES identity.user_account (user_id),
    CONSTRAINT ck_registration_full_name_nonempty CHECK (length(btrim(full_name)) > 0),
    CONSTRAINT ck_registration_email_normalized CHECK (work_email = lower(btrim(work_email))),
    CONSTRAINT ck_registration_username_normalized CHECK (username = lower(btrim(username))),
    CONSTRAINT ck_registration_status CHECK (status IN ('pending', 'approved', 'rejected', 'expired')),
    CONSTRAINT ck_registration_expiry CHECK (expires_at > requested_at),
    CONSTRAINT ck_registration_pending_hash CHECK (status <> 'pending' OR length(password_hash) > 0)
);

CREATE INDEX ix_registration_request_status_time
    ON identity.registration_request (status, requested_at DESC);
CREATE INDEX ix_registration_request_expiry
    ON identity.registration_request (expires_at)
    WHERE status = 'pending';
CREATE UNIQUE INDEX uq_registration_pending_username
    ON identity.registration_request (username)
    WHERE status = 'pending';
CREATE UNIQUE INDEX uq_registration_pending_email
    ON identity.registration_request (work_email)
    WHERE status = 'pending';

INSERT INTO identity.permission (permission_code, module_code, action_code, description)
VALUES
    ('identity_registration_read', 'identity', 'read', 'Xem hàng đợi yêu cầu cấp tài khoản.'),
    ('identity_registration_approve', 'identity', 'approve', 'Duyệt hoặc từ chối yêu cầu cấp tài khoản.')
ON CONFLICT (permission_code) DO NOTHING;

INSERT INTO identity.role_permission (role_id, permission_id)
SELECT role.role_id, permission.permission_id
FROM identity.role AS role
CROSS JOIN identity.permission AS permission
WHERE role.role_code = 'system_admin'
  AND permission.permission_code IN ('identity_registration_read', 'identity_registration_approve')
ON CONFLICT (role_id, permission_id) DO NOTHING;
